version: '3.7'

services:
  grip-ui-dev:
    container_name: grip-ui-dev
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - '..:/app'
      - '/app/node_modules'
    ports:
      - 1234:1234
    environment:
      - CHOKIDAR_USEPOLLING=true